### ISSUE TITLE
[Android Bootcamp] Project 3: Twitter Client ready for review

### ISSUE THREAD

**Issue by skipit** [skipit/TwitterTweets#1]
/cc @codepathreview @codepath

Was working on Tweet Detail Activity and could not complete. Have the intent ready and the client ready to query for tweetStatus.  Had autolink ready in Commit#eef62f5dd18d41bd7d9c346f7db55d882efafdc0, however had to remove it to work on other features. Could not get around to working around the issues with Android and OnClickListeners. 

Was a good project to do... lots of learning and reading.

**Comment by codepathreview** [comment]
:+1: Great work overall! Good job getting all the required stories done correctly along with a few extras. A few notes after checking out the code:
- Good job formatting the relative time stamp (correctly externalized the logic into Util class)
- Nice to see you used the `SwipeRefreshLayout` for easy timeline refreshes
- Nice touch adding the TextWatcher for counting characters
- Good to see you added ActiveAndroid annotations to the models for offline usage
- Consider using the [ProgressBar](http://guides.codepath.com/android/Handling-ProgressBars#actionbar-progress-bar) indicating network requests
- Consider adding null checks in JSON parsing for robust error handling
- Consider using [Parcelable over Serializable for model objects](https://guides.codepath.com/android/Using-Parcelable)
- Consider adding detailed tweet page in the next assignment.

Here's a detailed [Project 3 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_3_feedback) which covers the most common issues with this submitted project. Read through the feedback guide point-by-point to determine how you could improve your submission. 

Let us know if you have any other thoughts or questions about this assignment. Hopefully by now you feel pretty comfortable with all the major pieces to basic Android apps (Views, Controllers, ActionBar, Navigation, Models, Authentication, API Communication, Persistence, et al) and see how they all fit together. We are close now to a turning point in the course where you should be hitting a "critical mass" towards your knowledge of Android.
